[package]
name = "lord-ltp"
version = "0.1.0"
description = "Lord Transport Protocol local mempool for Lord"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1.0.90"
fs2 = "0.4"
hex.workspace = true
lord-storage = { path = "../lord-storage" }
opentimestamps = "0.2.0"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[dev-dependencies]
tempfile.workspace = true